### ISSUE TITLE
CUDA error when using hash encoder

### ISSUE THREAD

**Issue by kyleleey** [ashawkey/torch-ngp#14]
Hi, I add your hash encoder as a part of my network code(I only use the torch-ngp/hashencoder folder), and the compile seems not reporting any bugs, the hash encoder also outputs correctly, but the nn.Linear in my code following the hash encoder met CUDA error that won't show up without the hash encoder

```bash
 File "/home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1614378083779/work/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4037e2b2f2 in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f4037e2867b in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f4038084219 in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f4037e133a4 in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e0dda (0x7f408ed87dda in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e0e71 (0x7f408ed87e71 in /home/zz/miniconda3/envs/nerv/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1aa06a (0x555fc794b06a in /home/zz/miniconda3/envs/nerv/bin/python)
frame #7: <unknown function> + 0x10d0fc (0x555fc78ae0fc in /home/zz/miniconda3/envs/nerv/bin/python)
frame #8: <unknown function> + 0x10fbcc (0x555fc78b0bcc in /home/zz/miniconda3/envs/nerv/bin/python)
frame #9: <unknown function> + 0x217ca3 (0x555fc79b8ca3 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #10: <unknown function> + 0x10fd05 (0x555fc78b0d05 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #11: <unknown function> + 0x1aa047 (0x555fc794b047 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #12: <unknown function> + 0x10d0fc (0x555fc78ae0fc in /home/zz/miniconda3/envs/nerv/bin/python)
frame #13: <unknown function> + 0x10fbcc (0x555fc78b0bcc in /home/zz/miniconda3/envs/nerv/bin/python)
frame #14: <unknown function> + 0x217ca3 (0x555fc79b8ca3 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #15: <unknown function> + 0x10fd35 (0x555fc78b0d35 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #16: <unknown function> + 0x1aa047 (0x555fc794b047 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #17: <unknown function> + 0x110882 (0x555fc78b1882 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #18: <unknown function> + 0x1102a9 (0x555fc78b12a9 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #19: <unknown function> + 0x110293 (0x555fc78b1293 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #20: <unknown function> + 0x177d87 (0x555fc7918d87 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #21: PyDict_SetItemString + 0x4c (0x555fc791bccc in /home/zz/miniconda3/envs/nerv/bin/python)
frame #22: PyImport_Cleanup + 0xac (0x555fc798cc2c in /home/zz/miniconda3/envs/nerv/bin/python)
frame #23: Py_FinalizeEx + 0x79 (0x555fc79f34f9 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #24: Py_RunMain + 0x1bc (0x555fc79f687c in /home/zz/miniconda3/envs/nerv/bin/python)
frame #25: Py_BytesMain + 0x39 (0x555fc79f6c69 in /home/zz/miniconda3/envs/nerv/bin/python)
frame #26: __libc_start_main + 0xe7 (0x7f40c0bccbf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #27: <unknown function> + 0x1f7427 (0x555fc7998427 in /home/zz/miniconda3/envs/nerv/bin/python)
```

Maybe you could help me with this? Thanks a lot

**Comment by ashawkey** [comment]
Hi,
From this log, I cannot see any information related to hashencoder. Could you run the same code without hashencoder, or have you tried the official hashencoder implementation from [tinycudann](https://github.com/NVlabs/tiny-cuda-nn)?

**Comment by kyleleey** [comment]
The nn.Linear won't report this CUDA error if I don't use the hashencoder before, 

"the official hashencoder implementation from tinycudann" do you mean the extension in [https://github.com/nvlabs/tiny-cuda-nn#pytorch-extension](url)? Because the official implementation seems not based on pytorch so it's hard to implement in my codebase.

Btw, in your update logs in README, you mention now torch-ngp can use tiny-cuda-nn as an alternative backend, do you mean this? I wonder how to switch the backend to tiny-cuda-nn

**Comment by kyleleey** [comment]
Hi

I set the torch and cuda version exactly as in your README (torch1.10 and cuda 11.3), this time the CUDA error shows this:
```bash
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

So I rerun with `CUDA_LAUNCH_BLOCKING=1.` and get following error report, seems it comes from the hashgrid.py:
```bash
  File "/home/zz/workspace/codebase/model/hashencoder/hashgrid.py", line 41, in forward
    outputs = outputs.permute(1, 0, 2).reshape(B, L * C)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fad559e9d62 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c5f3 (0x7fad990965f3 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7fad99097002 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7fad559d3314 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x29eb89 (0x7fae1c3bdb89 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xadfbe1 (0x7fae1cbfebe1 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7fae1cbfeee2 in /home/zz/miniconda3/envs/torch-1.10/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #26: __libc_start_main + 0xe7 (0x7fae1f128bf7 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by ashawkey** [comment]
@kyleleey Yes, it does come from hashgrid encoder. Can you provide more details, like the parameters for hashencoder, and the input? A minimal reproducible example would be grateful.
Besides, [tinycudann ](https://github.com/NVlabs/tiny-cuda-nn) is based on pytorch, you can find an example of using it [here](https://github.com/ashawkey/torch-ngp/blob/main/nerf/network_tcnn.py#L27).

**Comment by kyleleey** [comment]
Hi

Thanks for the reply. It seems I accidentally base_resolution=1 in parameters for hashencoder, which trigger some boudary conditions. After changing the parameters, It works well.
